# Game Theory (Nash Equilbrium)

pip install nashpy

 **This is a game where our primary motive is to find the equilibrium.**
https://hub.gke2.mybinder.org/user/jupyterlab-jupyterlab-demo-2ujbcsdx/doc/tree/demo/a57cec0d-36ca-4575-84f5-cd1670f0e838.jfif.
The payoff to Player A will be 4 and player B will be 2 as you can see in Fig 2.This particular game has a very simple solution. For Player A , it is always better to play “Bottom” because his payoffs (4 or 2) from this strategy is always greater than Top (2 or 0). Similarly, for Player B, it is always better to play “Left” because his payoffs (4 or 2) is always greater than (2 or 0). Hence, the equilibrium strategy is for Player A to play “Bottom” and Player B to play “Left”. This brings us to the concept of dominant strategy.
![gt.jfif](attachment:gt.jfif)


**Dominant strategy**: There is one optimal strategy for each player irrespective of what strategy the other player adopts. Whatever choice B makes, A should always choose Bottom and whatever choice A makes B should always choose Left.
In this game, this is the equilibrium outcome of the game.



In [7]:
import nashpy as ns


In [8]:
#create game with the payoff matrix
import numpy as np
A= np.array([[2,0],[4,2]])#A is the row player
B=np.array([[4,2],[2,0]])#B is the column player
game1=ns.Game(A,B)
game1

Bi matrix game with payoff matrices:

Row player:
[[2 0]
 [4 2]]

Column player:
[[4 2]
 [2 0]]

In [11]:
#Find Nash equilibria with Support Enumeration
equilibria=game1.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([1., 0.]))


Since there are 2 strategies per player- Player A has strategies (Top, Bottom) and Player B has strategies (Left, Right).The output can be interpreted as: Player A chooses strategy 2 i.e. ‘Bottom’ as given by ‘1’ in the second position of the array and Player B chooses strategy 1 i.e. ‘Left’ as given by ‘1’ in the first position of the array. Hence, as we saw earlier (Bottom, Left) is the NE or outcome of this game.